export {default as About} from './about'
export {default as Contact} from './contact'
export {default as Footer} from './footer'
export {default as Image} from './image'
export {default as Portfolio} from './portfolio'
export {default as SideBar} from './sidebar'
export {default as Home} from './home'